server:
  port: 10000

spring:
  datasource:
    url: jdbc:postgresql://@config.datasource@:5432/wisdom_mall
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  application:
    name: wisdom-user
  cloud:
    nacos:
      discovery:
        server-addr: @config.nacos-addr@:8848
logging:
  level:
    top.ctong.wisdom.user: debug
    top.ctong.wisdom.common: debug

wisdom:
  security:
#    secret: 2cdc4c5a3d2541378b13fa8a206d393d
    expires: 1800