server:
  port: 10000
spring:
  config:
    import:
      - optional:nacos:database
  datasource:
    url: jdbc:postgresql://8.130.126.115:22031/wisdom_mall
    username: postgres
    password: @config.database.password@
    driver-class-name: org.postgresql.Driver
  application:
    name: wisdom-user
  cloud:
    nacos:
      discovery:
        server-addr: @config.nacos-addr@
      config:
        server-addr: @config.nacos-addr@
        namespace: 594c7e01-d402-461a-bf85-e1bd70c545cb
logging:
  level:
    top.ctong.wisdom.user: debug
    top.ctong.wisdom.common: debug

wisdom:
  security:
#    secret: 2cdc4c5a3d2541378b13fa8a206d393d
    expires: 1800
