server:
  port: 10300
spring:
  application:
    name: wisdom-third-party
  cloud:
    nacos:
      discovery:
        server-addr: @config.nacos-addr@
  data:
    redis:
      host: localhost
      port: 6379