server:
  port: 8840
spring:
  application:
    name: wisdom-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: wisdom_user
          uri: lb://wisdom-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/(?<path>.*),/$\{path}
        - id: wisdom_third_party
          uri: lb://wisdom-third-party
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/third-party/(?<path>.*),/$\{path}
logging:
  level:
    top.ctong.wisdom.gateway: debug