server:
  port: 10200
spring:
  application:
    name: wisdom-product
  datasource:
    url: jdbc:postgresql://@config.nacos-addr@/wisdom_mall
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      discovery:
        server-addr: @config.nacos-addr@

logging:
  level:
    top.ctong.wisdom.product: debug