// import { Inter } from 'next/font/google'
import BaseLayout from '#/layout/BaseLayout'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wisdom mall',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <BaseLayout>{children}</BaseLayout>
}
